<script setup lang="ts">
import { computed, ref, watch, watchEffect } from 'vue'
import { useRoute, RouterLink } from 'vue-router'
const route=useRoute(); const kind=computed(()=>String(route.params.kind)); const kinds=['attribute','tag','character','skill','item','effect']; const items=ref<Array<{id:string;name:string;key:string;entity_version:number}>>([]);const cursor=ref<string|null>(null);const query=ref('');const error=ref('');const references=ref<Array<{entity_id:string;field_path:string}>>([]);const loading=ref(false);const loaded=ref(false)
async function load(next?:string){loading.value=true;error.value='';references.value=[];try{const p=new URLSearchParams({limit:'50'});if(query.value)p.set('query',query.value);if(next)p.set('cursor',next);const r=await fetch(`/api/v1/entities/${kind.value}?${p}`);if(!r.ok)throw new Error('列表加载失败');const data=await r.json();items.value=data.items;cursor.value=data.next_cursor}catch(e){error.value=e instanceof Error?e.message:'列表加载失败'}finally{loading.value=false;loaded.value=true}}
async function archive(item:{id:string;entity_version:number}){if(!confirm('归档此对象？'))return;const r=await fetch(`/api/v1/entities/${kind.value}/${item.id}`,{method:'DELETE',headers:{'If-Match':`"${item.id}:${item.entity_version}"`}});if(r.ok){await load();return};const body=await r.json().catch(()=>null);references.value=body?.details?.references??[];error.value=body?.title??'归档失败'}
watchEffect(()=>{kind.value;void load()})
let debounce:number|undefined;watch(query,()=>{window.clearTimeout(debounce);debounce=window.setTimeout(()=>void load(),250)})
</script>
<template><section><RouterLink to="/projects">项目</RouterLink><nav aria-label="配置类型"><RouterLink v-for="entry in kinds" :key="entry" :to="`/config/${entry}`">{{ entry }}</RouterLink></nav><h1>{{ kind }} 配置</h1><RouterLink :to="`/config/${kind}/new`">新建</RouterLink><label>搜索 <input v-model="query"></label><p v-if="loading&&!loaded">正在首次加载…</p><p v-else-if="loading">正在刷新…</p><p v-else-if="error" role="alert">{{ error }} <button @click="load()">重试</button><ul v-if="references.length"><li v-for="ref in references" :key="`${ref.entity_id}${ref.field_path}`"><RouterLink :to="`/config/${kind}/${ref.entity_id}`">{{ ref.field_path }}</RouterLink></li></ul></p><p v-else-if="items.length===0&&query">没有匹配结果。<button @click="query=''">清除搜索</button></p><p v-else-if="items.length===0">暂无对象。<RouterLink :to="`/config/${kind}/new`">新建对象</RouterLink></p><ul v-else><li v-for="item in items" :key="item.id"><RouterLink :to="`/config/${kind}/${item.id}`">{{ item.name }}（{{ item.key }}）</RouterLink> <button @click="archive(item)">归档</button></li></ul><button v-if="cursor" @click="load(cursor)">下一页</button></section></template>
