/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/project-selections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["selectProjectDirectory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecentProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/recent/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openRecentProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["closeProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemas/entities/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEntitySchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEntities"];
        put?: never;
        post: operations["createEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{kind}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEntity"];
        put?: never;
        post?: never;
        delete: operations["deleteEntity"];
        options?: never;
        head?: never;
        patch: operations["patchEntity"];
        trace?: never;
    };
    "/validation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createValidationRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validation/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getValidationRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @description Server allocated UUIDv7.
         */
        UUIDv7: string;
        /** @description Canonical finite decimal128 string. */
        DecimalString: string;
        /** @description Canonical integer string. */
        IntegerString: string;
        Hash: string;
        /** @enum {string} */
        EntityKind: "character" | "skill" | "item" | "effect" | "tag" | "attribute";
        ProjectSelection: {
            /** @description Opaque short-lived process-local capability. */
            token: string;
            /** Format: date-time */
            expires_at: string;
        };
        OpenProjectRequest: {
            selection_token: string;
            /** @enum {string} */
            mode: "create" | "open";
        };
        Project: {
            id: components["schemas"]["UUIDv7"];
            name: string;
            db_schema_version: number;
        };
        EntitySchema: {
            kind: components["schemas"]["EntityKind"];
            schema_id: string;
            schema: {
                [key: string]: unknown;
            };
            ui_hints?: {
                [key: string]: unknown;
            };
            dsl_registry: components["schemas"]["DslRegistryMetadata"];
        };
        /** @description Read-only metadata for suggestions. It contains no executable code. */
        DslRegistryMetadata: {
            dsl_version: string;
            manifest_hash: components["schemas"]["Hash"];
            /** @constant */
            selector_template: "${scope:symbol}";
            scopes: ("self" | "source" | "target" | "scenario")[];
            units: components["schemas"]["DslUnitMetadata"][];
            functions: components["schemas"]["DslFunctionMetadata"][];
        };
        DslUnitMetadata: {
            name: string;
            /** @enum {string} */
            value_type: "decimal" | "integer";
            dimension: string;
            base: string;
        };
        DslFunctionMetadata: {
            name: string;
            signature: string;
            /** @constant */
            pure: true;
            implementation_version: string;
        };
        /** @enum {string} */
        EntityStatus: "active" | "archived";
        Entity: {
            id: components["schemas"]["UUIDv7"];
            kind: components["schemas"]["EntityKind"];
            key: string;
            name: string;
            description?: string;
            tag_ids: components["schemas"]["UUIDv7"][];
            balance_group?: string;
            status: components["schemas"]["EntityStatus"];
            /** @constant */
            schema_version: 1;
            payload: components["schemas"]["EntityPayload"];
            /** @description Namespaced opaque extension values. */
            extensions: {
                [key: string]: unknown;
            };
            entity_version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        EntityDraft: {
            key: string;
            name: string;
            description?: string;
            /** @default [] */
            tag_ids: components["schemas"]["UUIDv7"][];
            balance_group?: string;
            payload: components["schemas"]["EntityPayload"];
            /** @default {} */
            extensions: {
                [key: string]: unknown;
            };
        };
        EntityPatch: {
            key?: string;
            name?: string;
            description?: string;
            tag_ids?: components["schemas"]["UUIDv7"][];
            balance_group?: string;
            payload?: components["schemas"]["EntityPayload"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        EntityPayload: components["schemas"]["AttributePayload"] | components["schemas"]["TagPayload"] | components["schemas"]["CharacterPayload"] | components["schemas"]["SkillPayload"] | components["schemas"]["ItemPayload"] | components["schemas"]["EffectPayload"];
        AttributePayload: {
            /** @enum {string} */
            value_type: "integer" | "decimal" | "boolean";
            dimension: string;
            base_unit: string;
            default: components["schemas"]["DecimalString"] | boolean;
            min?: components["schemas"]["DecimalString"];
            max?: components["schemas"]["DecimalString"];
            display_scale?: components["schemas"]["DecimalString"];
        };
        TagPayload: {
            category: string;
            parent_tag_ids: components["schemas"]["UUIDv7"][];
        };
        FormulaBinding: {
            output_attribute_id: components["schemas"]["UUIDv7"];
            expression: string;
        };
        TargetSelector: {
            /** @enum {string} */
            type: "self" | "source" | "primary_target" | "all_targets" | "targets_with_tag";
            tag_id?: components["schemas"]["UUIDv7"];
        };
        TriggerRule: {
            /** @enum {string} */
            event: "on_use" | "on_hit" | "on_damage" | "on_heal" | "on_interval" | "on_effect_applied";
            condition?: string;
            target: components["schemas"]["TargetSelector"];
            effect_ids?: components["schemas"]["UUIDv7"][];
            termination_budget?: components["schemas"]["IntegerString"];
        };
        Modifier: {
            attribute_id: components["schemas"]["UUIDv7"];
            /** @enum {string} */
            operation: "Add" | "Multiply" | "Override" | "Max" | "Min";
            value: components["schemas"]["DecimalString"];
        };
        StackRule: {
            /** @enum {string} */
            operation: "Add" | "Multiply" | "Override" | "Max" | "Min";
            priority?: components["schemas"]["IntegerString"];
            max_stacks: components["schemas"]["IntegerString"];
            /** @enum {string} */
            refresh_policy: "refresh" | "replace" | "ignore";
            cap?: components["schemas"]["DecimalString"];
        };
        CharacterPayload: {
            attribute_values: components["schemas"]["FormulaBinding"][];
            skill_ids: components["schemas"]["UUIDv7"][];
            item_ids: components["schemas"]["UUIDv7"][];
            rule_blocks: components["schemas"]["TriggerRule"][];
        };
        SkillPayload: {
            costs: components["schemas"]["FormulaBinding"][];
            cooldown: components["schemas"]["IntegerString"];
            target_selector: components["schemas"]["TargetSelector"];
            effect_ids: components["schemas"]["UUIDv7"][];
            rule_blocks: components["schemas"]["TriggerRule"][];
        };
        ItemPayload: {
            slot: string;
            effect_ids: components["schemas"]["UUIDv7"][];
            attribute_modifiers: components["schemas"]["Modifier"][];
            enhance_tag_ids: components["schemas"]["UUIDv7"][];
            rule_blocks: components["schemas"]["TriggerRule"][];
        };
        EffectPayload: {
            duration: components["schemas"]["IntegerString"];
            modifiers: components["schemas"]["Modifier"][];
            trigger_blocks: components["schemas"]["TriggerRule"][];
            stack_rule: components["schemas"]["StackRule"];
        };
        RevisionSummary: {
            id: components["schemas"]["UUIDv7"];
            display_revision: number;
            config_hash: string;
            /** Format: date-time */
            created_at: string;
            validation: components["schemas"]["LocalValidationSummary"];
        };
        LocalValidationSummary: {
            run_id: components["schemas"]["UUIDv7"];
            /** @constant */
            scope: "LOCAL";
            error: number;
            block: number;
            warning: number;
            info: number;
        };
        SaveEntityResponse: {
            entity: components["schemas"]["Entity"];
            revision: components["schemas"]["RevisionSummary"];
        };
        /** @enum {string} */
        ValidationScope: "LOCAL" | "FULL";
        ValidationSource: components["schemas"]["WorkingValidationSource"] | components["schemas"]["RevisionValidationSource"];
        WorkingValidationSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WorkingValidationSource";
        };
        RevisionValidationSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "RevisionValidationSource";
            revision_id: components["schemas"]["UUIDv7"];
        };
        VersionManifest: {
            schema: string;
            dsl: string;
            registry: string;
            numeric_policy: string;
        };
        FormulaSpan: {
            /** @description UTF-8 byte offset */
            start_byte: number;
            /** @description UTF-8 byte offset */
            end_byte: number;
        };
        /** @enum {string} */
        ValidationSeverity: "ERROR" | "BLOCK" | "WARNING" | "INFO";
        SeveritySummary: {
            error: number;
            block: number;
            warning: number;
            info: number;
        };
        ValidationIssue: {
            severity: components["schemas"]["ValidationSeverity"];
            code: string;
            entity_id: components["schemas"]["UUIDv7"];
            /** @description RFC 6901 JSON Pointer. */
            field_path: string;
            formula_span?: components["schemas"]["FormulaSpan"] | null;
            ordinal?: number;
            message_key: string;
            /** @description Readable server-derived presentation text; excluded from validation identity and result hashes. */
            message: string;
            message_params?: {
                [key: string]: string;
            };
            fix_hint_key?: string;
            /** @description Readable server-derived presentation hint; excluded from validation identity and result hashes. */
            fix_hint?: string;
            evidence?: {
                [key: string]: string;
            };
            fingerprint: components["schemas"]["Hash"];
        };
        CreateValidationRunRequest: {
            source: components["schemas"]["ValidationSource"];
            scope: components["schemas"]["ValidationScope"];
            /** @description Required only for LOCAL; forbidden for FULL. */
            entity_ids?: components["schemas"]["UUIDv7"][];
        };
        ValidationRun: {
            id: components["schemas"]["UUIDv7"];
            source: components["schemas"]["ValidationSource"];
            scope: components["schemas"]["ValidationScope"];
            input_hash: components["schemas"]["Hash"];
            versions: components["schemas"]["VersionManifest"];
            /** @constant */
            status: "completed";
            summary: components["schemas"]["SeveritySummary"];
            result_hash: components["schemas"]["Hash"];
            /** Format: date-time */
            created_at: string;
            issues: components["schemas"]["ValidationIssue"][];
        };
        /** @enum {string} */
        ValidationGateResult: "PASS" | "REQUIRES_VALIDATION" | "BLOCKED";
        EntityPage: {
            items: components["schemas"]["Entity"][];
            next_cursor?: string | null;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @enum {string} */
            code: "INVALID_SELECTION" | "PROJECT_LOCKED" | "ACTIVE_PROJECT_CONFLICT" | "CLOSE_BLOCKED" | "UNSUPPORTED_KIND" | "UNSUPPORTED_SCHEMA" | "DUPLICATE_KEY" | "PRECONDITION_REQUIRED" | "REVISION_CONFLICT" | "ENTITY_REFERENCED" | "VALIDATION_FAILED" | "PROJECT_NOT_OPEN" | "INVALID_VALIDATION_REQUEST" | "INVALID_VALIDATION_SOURCE" | "INVALID_VALIDATION_SCOPE" | "INVALID_VALIDATION_TARGET" | "VALIDATION_SOURCE_NOT_FOUND" | "VALIDATION_RUN_NOT_FOUND" | "VALIDATION_STORAGE_FAILURE";
            retryable: boolean;
            request_id: string;
            entity_id?: components["schemas"]["UUIDv7"];
            field_path?: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description RFC 9457 problem */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Kind: components["schemas"]["EntityKind"];
        EntityID: components["schemas"]["UUIDv7"];
        ProjectID: components["schemas"]["UUIDv7"];
        ValidationRunID: components["schemas"]["UUIDv7"];
        /** @description Strong ETag returned by GET/create/patch. */
        IfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Strong ETag for the returned entity version. */
        EntityETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    selectProjectDirectory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory selected */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSelection"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    openProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenProjectRequest"];
            };
        };
        responses: {
            /** @description Project is active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Project created and active */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCurrentProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listRecentProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent project metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    openRecentProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent project opened and active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    closeProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project closed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getEntitySchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compiled registry schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySchema"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listEntities: {
        parameters: {
            query?: {
                query?: string;
                /** @description Opaque continuation cursor */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable entity page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityDraft"];
            };
        };
        responses: {
            /** @description Entity created in a new revision */
            201: {
                headers: {
                    ETag: components["headers"]["EntityETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveEntityResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity */
            200: {
                headers: {
                    ETag: components["headers"]["EntityETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteEntity: {
        parameters: {
            query?: never;
            header: {
                /** @description Strong ETag returned by GET/create/patch. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                kind: components["parameters"]["Kind"];
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity archived in a new revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveEntityResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    patchEntity: {
        parameters: {
            query?: never;
            header: {
                /** @description Strong ETag returned by GET/create/patch. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                kind: components["parameters"]["Kind"];
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityPatch"];
            };
        };
        responses: {
            /** @description Entity updated in a new revision */
            200: {
                headers: {
                    ETag: components["headers"]["EntityETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveEntityResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createValidationRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateValidationRunRequest"];
            };
        };
        responses: {
            /** @description Synchronously completed immutable validation run */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getValidationRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ValidationRunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
