/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/project-selections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["selectProjectDirectory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecentProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/recent/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openRecentProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["closeProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schemas/entities/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEntitySchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEntities"];
        put?: never;
        post: operations["createEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{kind}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEntity"];
        put?: never;
        post?: never;
        delete: operations["deleteEntity"];
        options?: never;
        head?: never;
        patch: operations["patchEntity"];
        trace?: never;
    };
    "/validation/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createValidationRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validation/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getValidationRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRevisions"];
        put?: never;
        post: operations["createRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revisions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revisions/{id}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRevisionDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revisions/{id}/graph-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ensures the exact immutable revision has one admitted Graph sync Job. A retry request requires a stable Idempotency-Key and never changes the revision or snapshot identity. */
        post: operations["ensureGraphSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revisions/{id}/graph-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Reads only the exact revision's persisted Graph observations. It never starts sync, rebuilds a projection, mutates a provider Snapshot, or falls back to another revision. */
        get: operations["getGraphStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/release-policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReleasePolicies"];
        put?: never;
        post: operations["createReleasePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReleases"];
        put?: never;
        post: operations["createRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/releases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamJobEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSimulationJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSimulationRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRuntimeCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @description Server allocated UUIDv7.
         */
        UUIDv7: string;
        /** @description Canonical finite decimal128 string. */
        DecimalString: string;
        /** @description Canonical integer string. */
        IntegerString: string;
        Hash: string;
        /** @enum {string} */
        EntityKind: "character" | "skill" | "item" | "effect" | "tag" | "attribute";
        ProjectSelection: {
            /** @description Opaque short-lived process-local capability. */
            token: string;
            /** Format: date-time */
            expires_at: string;
        };
        OpenProjectRequest: {
            selection_token: string;
            /** @enum {string} */
            mode: "create" | "open";
        };
        Project: {
            id: components["schemas"]["UUIDv7"];
            name: string;
            db_schema_version: number;
        };
        EntitySchema: {
            kind: components["schemas"]["EntityKind"];
            schema_id: string;
            schema: {
                [key: string]: unknown;
            };
            ui_hints?: {
                [key: string]: unknown;
            };
            dsl_registry: components["schemas"]["DslRegistryMetadata"];
        };
        /** @description Read-only metadata for suggestions. It contains no executable code. */
        DslRegistryMetadata: {
            dsl_version: string;
            manifest_hash: components["schemas"]["Hash"];
            /** @constant */
            selector_template: "${scope:symbol}";
            scopes: ("self" | "source" | "target" | "scenario")[];
            units: components["schemas"]["DslUnitMetadata"][];
            functions: components["schemas"]["DslFunctionMetadata"][];
        };
        DslUnitMetadata: {
            name: string;
            /** @enum {string} */
            value_type: "decimal" | "integer";
            dimension: string;
            base: string;
        };
        DslFunctionMetadata: {
            name: string;
            signature: string;
            /** @constant */
            pure: true;
            implementation_version: string;
        };
        /** @enum {string} */
        EntityStatus: "active" | "archived";
        Entity: {
            id: components["schemas"]["UUIDv7"];
            kind: components["schemas"]["EntityKind"];
            key: string;
            name: string;
            description?: string;
            tag_ids: components["schemas"]["UUIDv7"][];
            balance_group?: string;
            status: components["schemas"]["EntityStatus"];
            /** @constant */
            schema_version: 1;
            payload: components["schemas"]["EntityPayload"];
            /** @description Namespaced opaque extension values. */
            extensions: {
                [key: string]: unknown;
            };
            entity_version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        EntityDraft: {
            key: string;
            name: string;
            description?: string;
            /** @default [] */
            tag_ids: components["schemas"]["UUIDv7"][];
            balance_group?: string;
            payload: components["schemas"]["EntityPayload"];
            /** @default {} */
            extensions: {
                [key: string]: unknown;
            };
        };
        EntityPatch: {
            key?: string;
            name?: string;
            description?: string;
            tag_ids?: components["schemas"]["UUIDv7"][];
            balance_group?: string;
            payload?: components["schemas"]["EntityPayload"];
            extensions?: {
                [key: string]: unknown;
            };
        };
        EntityPayload: components["schemas"]["AttributePayload"] | components["schemas"]["TagPayload"] | components["schemas"]["CharacterPayload"] | components["schemas"]["SkillPayload"] | components["schemas"]["ItemPayload"] | components["schemas"]["EffectPayload"];
        AttributePayload: {
            /** @enum {string} */
            value_type: "integer" | "decimal" | "boolean";
            dimension: string;
            base_unit: string;
            default: components["schemas"]["DecimalString"] | boolean;
            min?: components["schemas"]["DecimalString"];
            max?: components["schemas"]["DecimalString"];
            display_scale?: components["schemas"]["DecimalString"];
        };
        TagPayload: {
            category: string;
            parent_tag_ids: components["schemas"]["UUIDv7"][];
        };
        FormulaBinding: {
            output_attribute_id: components["schemas"]["UUIDv7"];
            expression: string;
        };
        TargetSelector: {
            /** @enum {string} */
            type: "self" | "source" | "primary_target" | "all_targets" | "targets_with_tag";
            tag_id?: components["schemas"]["UUIDv7"];
        };
        TriggerRule: {
            /** @enum {string} */
            event: "on_use" | "on_hit" | "on_damage" | "on_heal" | "on_interval" | "on_effect_applied";
            condition?: string;
            target: components["schemas"]["TargetSelector"];
            effect_ids?: components["schemas"]["UUIDv7"][];
            termination_budget?: components["schemas"]["IntegerString"];
        };
        Modifier: {
            attribute_id: components["schemas"]["UUIDv7"];
            /** @enum {string} */
            operation: "Add" | "Multiply" | "Override" | "Max" | "Min";
            value: components["schemas"]["DecimalString"];
        };
        StackRule: {
            /** @enum {string} */
            operation: "Add" | "Multiply" | "Override" | "Max" | "Min";
            priority?: components["schemas"]["IntegerString"];
            max_stacks: components["schemas"]["IntegerString"];
            /** @enum {string} */
            refresh_policy: "refresh" | "replace" | "ignore";
            cap?: components["schemas"]["DecimalString"];
        };
        CharacterPayload: {
            attribute_values: components["schemas"]["FormulaBinding"][];
            skill_ids: components["schemas"]["UUIDv7"][];
            item_ids: components["schemas"]["UUIDv7"][];
            rule_blocks: components["schemas"]["TriggerRule"][];
        };
        SkillPayload: {
            costs: components["schemas"]["FormulaBinding"][];
            cooldown: components["schemas"]["IntegerString"];
            target_selector: components["schemas"]["TargetSelector"];
            effect_ids: components["schemas"]["UUIDv7"][];
            rule_blocks: components["schemas"]["TriggerRule"][];
        };
        ItemPayload: {
            slot: string;
            effect_ids: components["schemas"]["UUIDv7"][];
            attribute_modifiers: components["schemas"]["Modifier"][];
            enhance_tag_ids: components["schemas"]["UUIDv7"][];
            rule_blocks: components["schemas"]["TriggerRule"][];
        };
        EffectPayload: {
            duration: components["schemas"]["IntegerString"];
            modifiers: components["schemas"]["Modifier"][];
            trigger_blocks: components["schemas"]["TriggerRule"][];
            stack_rule: components["schemas"]["StackRule"];
        };
        RevisionSummary: {
            id: components["schemas"]["UUIDv7"];
            display_revision: number;
            config_hash: string;
            /** Format: date-time */
            created_at: string;
            validation: components["schemas"]["LocalValidationSummary"];
        };
        VersionContributor: {
            capability_id: string;
            contract_version: string;
            /** @description Immutable implementation identity; null only when unavailable at revision creation. */
            implementation_version?: string | null;
            /** @enum {string} */
            state: "registered" | "unregistered";
        };
        RevisionVersionManifest: {
            entries: components["schemas"]["VersionContributor"][];
            hash: components["schemas"]["Hash"];
        };
        RevisionMetadata: {
            revision_id: components["schemas"]["UUIDv7"];
            config_hash: components["schemas"]["Hash"];
            name?: string | null;
            description?: string | null;
            parent_revision_id?: components["schemas"]["UUIDv7"] | null;
            source_revision_id?: components["schemas"]["UUIDv7"] | null;
            source_release_id?: components["schemas"]["UUIDv7"] | null;
            version_manifest: components["schemas"]["RevisionVersionManifest"];
            /** Format: date-time */
            created_at: string;
        };
        /**
         * @description Derived read model only; it never mutates immutable revision history.
         * @enum {string}
         */
        RevisionStatus: "working" | "candidate" | "active_release" | "history";
        RevisionHistoryItem: {
            id: components["schemas"]["UUIDv7"];
            display_revision: number;
            config_hash: components["schemas"]["Hash"];
            metadata: components["schemas"]["RevisionMetadata"];
            status: components["schemas"]["RevisionStatus"][];
        };
        RevisionDetail: components["schemas"]["RevisionHistoryItem"] & {
            timeline: components["schemas"]["RevisionTimeline"];
        };
        RevisionPage: {
            items: components["schemas"]["RevisionHistoryItem"][];
            /** @description Opaque stable cursor ordered by display revision and revision ID. */
            next_cursor?: string | null;
        };
        RevisionTimelineEvent: {
            id: string;
            /** Format: date-time */
            occurred_at: string;
            /** @enum {string} */
            type: "revision_created" | "validation_completed" | "gate_evaluated" | "release_queued" | "release_completed" | "active_pointer_changed";
            revision_id: components["schemas"]["UUIDv7"];
            subject_id?: string | null;
            status?: string | null;
        };
        /** @description Stable chronological projection of immutable facts; revision status is not stored on the revision. */
        RevisionTimeline: components["schemas"]["RevisionTimelineEvent"][];
        CurrentWorkingPrecondition: {
            revision_id: components["schemas"]["UUIDv7"];
            /** @description Optional strong entity ETag when a single entity is the source of the operation. */
            entity_etag?: string | null;
        };
        CreateCheckpointRevision: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "checkpoint";
            current_working: components["schemas"]["CurrentWorkingPrecondition"];
            name?: string;
            description?: string;
        };
        RestoreReleaseRevision: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "restore_release";
            current_working: components["schemas"]["CurrentWorkingPrecondition"];
            source_release_id: components["schemas"]["UUIDv7"];
        };
        CreateRevisionRequest: components["schemas"]["CreateCheckpointRevision"] | components["schemas"]["RestoreReleaseRevision"];
        /** @enum {string} */
        FieldChangeKind: "ADD" | "DELETE" | "MOVE" | "MODIFY";
        FieldChange: {
            entity_id: components["schemas"]["UUIDv7"];
            entity_kind: components["schemas"]["EntityKind"];
            /** @description RFC 6901 JSON Pointer. */
            path: string;
            kind: components["schemas"]["FieldChangeKind"];
            /** @description Canonical JSON value before the change. */
            old_value?: unknown;
            /** @description Canonical JSON value after the change. */
            new_value?: unknown;
            old_ordinal?: number;
            new_ordinal?: number;
        };
        /** @enum {string} */
        DiffBaselineState: "AVAILABLE" | "NO_BASELINE";
        RevisionDiff: {
            base_revision_id: components["schemas"]["UUIDv7"];
            target_revision_id: components["schemas"]["UUIDv7"];
            base_config_hash: components["schemas"]["Hash"];
            target_config_hash: components["schemas"]["Hash"];
            baseline_state: components["schemas"]["DiffBaselineState"];
            changes: components["schemas"]["FieldChange"][];
        };
        ReleaseMetric: {
            id: string;
            required: boolean;
        };
        ReleaseScene: {
            id: string;
            required: boolean;
            metrics: components["schemas"]["ReleaseMetric"][];
        };
        CapabilityGateRequirement: {
            capability_id: string;
            gate_id: string;
            contract_version: string;
            implementation_version?: string | null;
        };
        ReleasePolicyDefinition: {
            scenes: components["schemas"]["ReleaseScene"][];
            samples: number;
            threshold_id: string;
            /** @constant */
            threshold_enabled: true;
            capabilities: components["schemas"]["CapabilityGateRequirement"][];
        };
        CreateReleasePolicyRequest: components["schemas"]["ReleasePolicyDefinition"];
        ReleasePolicy: components["schemas"]["ReleasePolicyDefinition"] & {
            id: components["schemas"]["UUIDv7"];
            display_version: number;
            policy_hash: components["schemas"]["Hash"];
            /** Format: date-time */
            created_at: string;
        };
        ReleasePolicyPage: {
            items: components["schemas"]["ReleasePolicy"][];
            /** @description Opaque stable cursor ordered by display version and ID. */
            next_cursor?: string | null;
        };
        GateEvidence: {
            capability_id?: string;
            gate_id: string;
            result_id: components["schemas"]["UUIDv7"];
            result_hash: components["schemas"]["Hash"];
            /** @enum {string} */
            state: "PASS" | "WARNING" | "BLOCK" | "UNAVAILABLE" | "STALE";
            evidence_url?: string | null;
        };
        ReleaseConfirmation: {
            /** @enum {string} */
            kind: "establish_baseline" | "acknowledge_warning" | "numeric_override";
            /** @constant */
            confirmed: true;
            reason?: string | null;
        };
        CreateReleaseRequest: {
            candidate_revision_id: components["schemas"]["UUIDv7"];
            config_hash: components["schemas"]["Hash"];
            version_manifest_hash: components["schemas"]["Hash"];
            policy_id: components["schemas"]["UUIDv7"];
            /** @description Explicit null establishes a first-release baseline. */
            expected_baseline_release_id: components["schemas"]["UUIDv7"] | null;
            notes?: string;
            confirmations: components["schemas"]["ReleaseConfirmation"][];
            /** @description Read-only client echo for audit consistency; server remains authoritative. */
            gate_evidence?: components["schemas"]["GateEvidence"][];
        };
        ActiveReleasePointer: {
            release_id?: components["schemas"]["UUIDv7"] | null;
            generation: number;
        };
        Release: {
            id: components["schemas"]["UUIDv7"];
            revision_id: components["schemas"]["UUIDv7"];
            policy_id: components["schemas"]["UUIDv7"];
            baseline_release_id?: components["schemas"]["UUIDv7"] | null;
            intent_id: components["schemas"]["UUIDv7"];
            notes?: string;
            gate_evidence: components["schemas"]["GateEvidence"][];
            confirmations: components["schemas"]["ReleaseConfirmation"][];
            /** Format: date-time */
            created_at: string;
        };
        ReleaseDetail: components["schemas"]["Release"] & {
            active_pointer: components["schemas"]["ActiveReleasePointer"];
        };
        ReleasePage: {
            items: components["schemas"]["Release"][];
            next_cursor?: string | null;
        };
        ReleaseJobAccepted: {
            job_id: components["schemas"]["UUIDv7"];
            /** Format: uri-reference */
            location: string;
        };
        /** @enum {string} */
        GraphSyncIntent: "ensure" | "retry";
        GraphSyncEnsureRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            intent: "ensure";
        };
        GraphSyncRetryRequest: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            intent: "retry";
            /** @description The terminal Graph Job being retried; retry eligibility remains server-authoritative. */
            retry_of_job_id: components["schemas"]["UUIDv7"];
        };
        GraphSyncRequest: components["schemas"]["GraphSyncEnsureRequest"] | components["schemas"]["GraphSyncRetryRequest"];
        GraphSyncJobAccepted: {
            job: components["schemas"]["Job"];
            /** Format: uri-reference */
            location: string;
        };
        /** @enum {string} */
        GraphPipelineState: "saved" | "validating" | "blocked_validation" | "graph_queued" | "graph_building" | "graph_ready" | "graph_failed";
        /** @enum {string} */
        GraphFreshness: "fresh" | "stale" | "unknown";
        /** @enum {string} */
        GraphComponentState: "ready" | "building" | "failed" | "unavailable" | "unknown";
        GraphComponent: {
            /** @enum {string} */
            name: "graph" | "fts" | "vector" | "rerank";
            state: components["schemas"]["GraphComponentState"];
            /** @description Safe component diagnostic only. */
            detail?: string | null;
        };
        GraphEvidence: {
            key: string;
            /** @description Safe identity */
            value: string;
        };
        GraphWarning: {
            code: string;
            message: string;
            request_id?: string | null;
        };
        GraphSafeError: {
            code: string;
            retryable: boolean;
            message?: string | null;
            request_id?: string | null;
            /** @description Stable provider code only; raw provider error bodies are never exposed. */
            provider_code?: string | null;
        };
        GraphProjectionSummary: {
            projection_schema_version: string;
            projector_version: string;
            graph_manifest_hash: components["schemas"]["Hash"];
            node_count: number;
            edge_count: number;
        };
        GraphProviderObservation: {
            /** @description Stable project UUID namespace. */
            namespace: string;
            version: components["schemas"]["UUIDv7"];
            task_id?: components["schemas"]["UUIDv7"] | null;
            /** @enum {string} */
            status: "queued" | "building" | "ready" | "failed" | "unavailable" | "unknown";
            query_ready: boolean;
            components: components["schemas"]["GraphComponent"][];
            /** Format: date-time */
            observed_at: string;
        };
        /** @enum {string} */
        GraphAction: "retry" | "wait" | "inspect" | "none";
        GraphStatus: {
            revision_id: components["schemas"]["UUIDv7"];
            config_hash: components["schemas"]["Hash"];
            pipeline_state: components["schemas"]["GraphPipelineState"];
            freshness: components["schemas"]["GraphFreshness"];
            freshness_reasons: string[];
            validation_run_id?: components["schemas"]["UUIDv7"] | null;
            /** @enum {string|null} */
            validation_result?: "PASS" | "REQUIRES_VALIDATION" | "BLOCKED" | null;
            projection?: components["schemas"]["GraphProjectionSummary"] | null;
            job?: components["schemas"]["Job"] | null;
            job_phase?: string | null;
            job_progress?: number | null;
            provider?: components["schemas"]["GraphProviderObservation"] | null;
            /** @enum {string|null} */
            impact_state?: "queued" | "consumed" | "failed" | "unavailable" | null;
            warnings: components["schemas"]["GraphWarning"][];
            error?: components["schemas"]["GraphSafeError"] | null;
            actions: components["schemas"]["GraphAction"][];
            evidence: components["schemas"]["GraphEvidence"][];
        };
        /** @enum {string} */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "canceled" | "interrupted";
        JobEvent: {
            job_id: components["schemas"]["UUIDv7"];
            ordinal: number;
            phase: string;
            progress: number;
            warning?: string | null;
            error?: string | null;
            result_type?: string | null;
            result_id?: components["schemas"]["UUIDv7"] | null;
            /** Format: uri-reference */
            result_url?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Job: {
            id: components["schemas"]["UUIDv7"];
            /** @description Registered durable Job kind. Unknown persisted kinds are returned only through a registered projection. */
            kind: string;
            revision_id: components["schemas"]["UUIDv7"];
            status: components["schemas"]["JobStatus"];
            request_hash: components["schemas"]["Hash"];
            /** Format: uri-reference */
            events_url: string;
            /** @description Polling fallback cadence when SSE is unavailable. */
            poll_after_ms: number;
            latest_event_ordinal?: number;
            result_type?: string | null;
            result_id?: components["schemas"]["UUIDv7"] | null;
            /** Format: uri-reference */
            result_url?: string | null;
            /** @description Monotonic persisted cancellation generation. */
            cancel_generation?: number;
            /**
             * Format: date-time
             * @description Time the current cancellation intent was recorded
             */
            cancel_requested_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SimulationSource: {
            revision_id: components["schemas"]["UUIDv7"];
        } | {
            release_id: components["schemas"]["UUIDv7"];
        };
        SimulationMetricRequest: {
            id: string;
            version: string;
        };
        SimulationBudget: {
            max_events?: number;
            max_steps?: number;
            max_runtime_ms?: number;
        };
        CreateSimulationJobRequest: {
            source: components["schemas"]["SimulationSource"];
            scene_id: string;
            scene_version: string;
            parameters?: {
                [key: string]: unknown;
            };
            metrics: components["schemas"]["SimulationMetricRequest"][];
            /** @default 1000 */
            sample_count: number;
            seed?: number;
            budget?: components["schemas"]["SimulationBudget"];
            verify_run_id?: components["schemas"]["UUIDv7"];
        };
        SimulationJobAccepted: {
            job: components["schemas"]["Job"];
            /** Format: uri-reference */
            location: string;
        };
        SimulationRun: {
            id: components["schemas"]["UUIDv7"];
            job_id: components["schemas"]["UUIDv7"];
            revision_id: components["schemas"]["UUIDv7"];
            input_hash: components["schemas"]["Hash"];
            fingerprint_hash: components["schemas"]["Hash"];
            result_hash: components["schemas"]["Hash"];
            canonical_result: string;
            reproducible: boolean;
            reasons: string[];
            /** Format: date-time */
            created_at: string;
        };
        ReleaseDisabledReason: {
            capability_id: string;
            gate_id: string;
            /** @enum {string} */
            code: "MISSING" | "INCOMPATIBLE" | "UNAVAILABLE";
            detail?: string | null;
        };
        ReleaseCapability: {
            /** @description Server-authoritative release-entry state; it is never computed by the client. */
            enabled: boolean;
            disabled_reasons: components["schemas"]["ReleaseDisabledReason"][];
        };
        /** @description Safe runtime availability projection. It deliberately omits backup credentials, service endpoints, and client-computed Gate pass state. */
        RuntimeCapabilities: {
            release: components["schemas"]["ReleaseCapability"];
            graph: components["schemas"]["GraphRuntimeCapability"];
        };
        /** @description Server-authoritative Graph provider health and compatibility. Graph release readiness remains a Gate result for an exact candidate revision. */
        GraphRuntimeCapability: {
            available: boolean;
            compatible: boolean;
            required_capabilities: string[];
            degradations: string[];
            disabled_reasons: string[];
            /** @description Same stable Graph capability reasons consumed when Graph disables release admission. */
            release_disabled_reasons: string[];
            /** Format: date-time */
            observed_at?: string | null;
        };
        LocalValidationSummary: {
            run_id: components["schemas"]["UUIDv7"];
            /** @constant */
            scope: "LOCAL";
            error: number;
            block: number;
            warning: number;
            info: number;
        };
        SaveEntityResponse: {
            entity: components["schemas"]["Entity"];
            revision: components["schemas"]["RevisionSummary"];
        };
        /** @enum {string} */
        ValidationScope: "LOCAL" | "FULL";
        ValidationSource: components["schemas"]["WorkingValidationSource"] | components["schemas"]["RevisionValidationSource"];
        WorkingValidationSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "WorkingValidationSource";
        };
        RevisionValidationSource: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "RevisionValidationSource";
            revision_id: components["schemas"]["UUIDv7"];
        };
        VersionManifest: {
            schema: string;
            dsl: string;
            registry: string;
            numeric_policy: string;
        };
        FormulaSpan: {
            /** @description UTF-8 byte offset */
            start_byte: number;
            /** @description UTF-8 byte offset */
            end_byte: number;
        };
        /** @enum {string} */
        ValidationSeverity: "ERROR" | "BLOCK" | "WARNING" | "INFO";
        SeveritySummary: {
            error: number;
            block: number;
            warning: number;
            info: number;
        };
        ValidationIssue: {
            severity: components["schemas"]["ValidationSeverity"];
            code: string;
            entity_id: components["schemas"]["UUIDv7"];
            /** @description RFC 6901 JSON Pointer. */
            field_path: string;
            formula_span?: components["schemas"]["FormulaSpan"] | null;
            ordinal?: number;
            message_key: string;
            /** @description Readable server-derived presentation text; excluded from validation identity and result hashes. */
            message: string;
            message_params?: {
                [key: string]: string;
            };
            fix_hint_key?: string;
            /** @description Readable server-derived presentation hint; excluded from validation identity and result hashes. */
            fix_hint?: string;
            evidence?: {
                [key: string]: string;
            };
            fingerprint: components["schemas"]["Hash"];
        };
        CreateValidationRunRequest: {
            source: components["schemas"]["ValidationSource"];
            scope: components["schemas"]["ValidationScope"];
            /** @description Required only for LOCAL; forbidden for FULL. */
            entity_ids?: components["schemas"]["UUIDv7"][];
        };
        ValidationRun: {
            id: components["schemas"]["UUIDv7"];
            source: components["schemas"]["ValidationSource"];
            scope: components["schemas"]["ValidationScope"];
            input_hash: components["schemas"]["Hash"];
            versions: components["schemas"]["VersionManifest"];
            /** @constant */
            status: "completed";
            summary: components["schemas"]["SeveritySummary"];
            result_hash: components["schemas"]["Hash"];
            /** Format: date-time */
            created_at: string;
            issues: components["schemas"]["ValidationIssue"][];
        };
        /** @enum {string} */
        ValidationGateResult: "PASS" | "REQUIRES_VALIDATION" | "BLOCKED";
        EntityPage: {
            items: components["schemas"]["Entity"][];
            next_cursor?: string | null;
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            /** @enum {string} */
            code: "INVALID_SELECTION" | "PROJECT_LOCKED" | "ACTIVE_PROJECT_CONFLICT" | "CLOSE_BLOCKED" | "UNSUPPORTED_KIND" | "UNSUPPORTED_SCHEMA" | "DUPLICATE_KEY" | "PRECONDITION_REQUIRED" | "REVISION_CONFLICT" | "ENTITY_REFERENCED" | "VALIDATION_FAILED" | "PROJECT_NOT_OPEN" | "INVALID_VALIDATION_REQUEST" | "INVALID_VALIDATION_SOURCE" | "INVALID_VALIDATION_SCOPE" | "INVALID_VALIDATION_TARGET" | "VALIDATION_SOURCE_NOT_FOUND" | "VALIDATION_RUN_NOT_FOUND" | "VALIDATION_STORAGE_FAILURE" | "REVISION_NOT_FOUND" | "REVISION_IMMUTABLE" | "DIFF_BASE_INVALID" | "RELEASE_POLICY_INVALID" | "RELEASE_CAPABILITY_DISABLED" | "RELEASE_PREFLIGHT_FAILED" | "RELEASE_BASE_CONFLICT" | "IDEMPOTENCY_CONFLICT" | "MANDATORY_BACKUP_FAILED" | "MIGRATION_BACKUP_REQUIRED" | "INVALID_CONFIRMATION" | "HISTORY_NOT_FOUND" | "STORAGE_FAILURE" | "EXTERNAL_SERVICE_FAILURE" | "GRAPH_VALIDATION_REQUIRED" | "GRAPH_VALIDATION_BLOCKED" | "PROJECTOR_VERSION_UNAVAILABLE" | "GRAPH_CAPABILITY_UNAVAILABLE" | "BASE_SNAPSHOT_NOT_FOUND" | "BASE_SNAPSHOT_NOT_READY" | "CONTENT_HASH_MISMATCH" | "CONTENT_HASH_CONFLICT" | "PROVIDER_TASK_FAILED" | "GRAPH_RETRY_EXHAUSTED" | "GRAPH_RETRY_NOT_SAFE" | "GRAPH_STATUS_UNAVAILABLE";
            retryable: boolean;
            request_id: string;
            entity_id?: components["schemas"]["UUIDv7"];
            field_path?: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description RFC 9457 problem */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        Kind: components["schemas"]["EntityKind"];
        EntityID: components["schemas"]["UUIDv7"];
        ProjectID: components["schemas"]["UUIDv7"];
        ValidationRunID: components["schemas"]["UUIDv7"];
        RevisionID: components["schemas"]["UUIDv7"];
        ReleaseID: components["schemas"]["UUIDv7"];
        JobID: components["schemas"]["UUIDv7"];
        SimulationRunID: components["schemas"]["UUIDv7"];
        /** @description Reuse with byte-equivalent canonical input returns the original Job; changed input returns idempotency conflict. */
        IdempotencyKey: string;
        /** @description Required when graph-sync intent is retry; reuse returns the original retry Job and changed retry input conflicts. It is ignored for ensure. */
        GraphRetryIdempotencyKey: string;
        /** @description Resume SSE delivery strictly after this persisted event ordinal. */
        LastEventID: number;
        /** @description Strong ETag returned by GET/create/patch. */
        IfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Strong ETag for the returned entity version. */
        EntityETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    selectProjectDirectory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory selected */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSelection"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    openProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenProjectRequest"];
            };
        };
        responses: {
            /** @description Project is active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Project created and active */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getCurrentProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listRecentProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent project metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    openRecentProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProjectID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent project opened and active */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    closeProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project closed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Problem"];
        };
    };
    getEntitySchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Compiled registry schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySchema"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listEntities: {
        parameters: {
            query?: {
                query?: string;
                /** @description Opaque continuation cursor */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable entity page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityDraft"];
            };
        };
        responses: {
            /** @description Entity created in a new revision */
            201: {
                headers: {
                    ETag: components["headers"]["EntityETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveEntityResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["Kind"];
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity */
            200: {
                headers: {
                    ETag: components["headers"]["EntityETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    deleteEntity: {
        parameters: {
            query?: never;
            header: {
                /** @description Strong ETag returned by GET/create/patch. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                kind: components["parameters"]["Kind"];
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entity archived in a new revision */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveEntityResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    patchEntity: {
        parameters: {
            query?: never;
            header: {
                /** @description Strong ETag returned by GET/create/patch. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                kind: components["parameters"]["Kind"];
                id: components["parameters"]["EntityID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntityPatch"];
            };
        };
        responses: {
            /** @description Entity updated in a new revision */
            200: {
                headers: {
                    ETag: components["headers"]["EntityETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveEntityResponse"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createValidationRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateValidationRunRequest"];
            };
        };
        responses: {
            /** @description Synchronously completed immutable validation run */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getValidationRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ValidationRunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listRevisions: {
        parameters: {
            query?: {
                /** @description Opaque stable continuation cursor. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stable revision history page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createRevision: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRevisionRequest"];
            };
        };
        responses: {
            /** @description Immutable checkpoint or forward-rollback revision created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RevisionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable revision detail and derived status timeline */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRevisionDiff: {
        parameters: {
            query: {
                /** @description Immutable base revision; no server-side fallback is permitted. */
                base: components["schemas"]["UUIDv7"];
            };
            header?: never;
            path: {
                id: components["parameters"]["RevisionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deterministic structured revision diff */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionDiff"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    ensureGraphSync: {
        parameters: {
            query?: never;
            header?: {
                /** @description Required when graph-sync intent is retry; reuse returns the original retry Job and changed retry input conflicts. It is ignored for ensure. */
                "Idempotency-Key"?: components["parameters"]["GraphRetryIdempotencyKey"];
            };
            path: {
                id: components["parameters"]["RevisionID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphSyncRequest"];
            };
        };
        responses: {
            /** @description Existing or newly admitted durable Graph Job. The Location header and job URLs identify the same Job. */
            202: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphSyncJobAccepted"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getGraphStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["RevisionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exact revision Graph state and last safe provider observation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphStatus"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listReleasePolicies: {
        parameters: {
            query?: {
                /** @description Opaque stable continuation cursor. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable release-policy history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasePolicyPage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createReleasePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReleasePolicyRequest"];
            };
        };
        responses: {
            /** @description New immutable release-policy version */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasePolicy"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    listReleases: {
        parameters: {
            query?: {
                /** @description Opaque stable continuation cursor. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only release history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleasePage"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createRelease: {
        parameters: {
            query?: never;
            header: {
                /** @description Reuse with byte-equivalent canonical input returns the original Job; changed input returns idempotency conflict. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReleaseRequest"];
            };
        };
        responses: {
            /** @description Release preflight accepted and durable Job queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseJobAccepted"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ReleaseID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable release detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseDetail"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable registered Job state; clients may poll using poll_after_ms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    streamJobEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resume SSE delivery strictly after this persisted event ordinal. */
                "Last-Event-ID"?: components["parameters"]["LastEventID"];
            };
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted Job events in ordinal order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation intent persisted for a registered Job; feature workers resolve it at their documented safe boundary */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    createSimulationJob: {
        parameters: {
            query?: never;
            header: {
                /** @description Reuse with byte-equivalent canonical input returns the original Job; changed input returns idempotency conflict. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSimulationJobRequest"];
            };
        };
        responses: {
            /** @description Existing or newly admitted durable simulation Job. */
            202: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationJobAccepted"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getSimulationRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SimulationRunID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable simulation result with read-time reproducibility projection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRun"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getRuntimeCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-authoritative release capability state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeCapabilities"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
