<script setup lang="ts">
import { computed } from 'vue'
import type { EntityKind, EntitySchema, Payload } from '@/forms/registry'

const props = defineProps<{ kind: EntityKind; modelValue: Payload; dsl?: EntitySchema['dsl_registry'] }>()
const emit = defineEmits<{ 'update:modelValue': [value: Payload]; changed: [] }>()
const p = computed(() => props.modelValue as unknown as Record<string, any>)
function changed() { emit('update:modelValue', { ...p.value } as Payload); emit('changed') }
function add(name: string, value: Record<string, unknown> | string = '') { (p.value[name] ??= []).push(value); changed() }
function remove(name: string, index: number) { p.value[name].splice(index, 1); changed() }
</script>
<template>
  <fieldset class="payload-form"><legend>配置字段</legend>
    <template v-if="kind === 'attribute'">
      <label>数值类型 <select data-field-path="/payload/value_type" v-model="p.value_type" @change="changed"><option>integer</option><option>decimal</option><option>boolean</option></select></label>
      <label>维度 <input data-field-path="/payload/dimension" v-model="p.dimension" @input="changed"></label><label>基础单位 <input data-field-path="/payload/base_unit" v-model="p.base_unit" @input="changed"></label>
      <label>默认值 <input data-field-path="/payload/default" type="number" v-model.number="p.default" @input="changed"></label><label>最小值 <input data-field-path="/payload/min" type="number" v-model.number="p.min" @input="changed"></label><label>最大值 <input data-field-path="/payload/max" type="number" v-model.number="p.max" @input="changed"></label><label>显示倍率 <input data-field-path="/payload/display_scale" type="number" v-model.number="p.display_scale" @input="changed"></label>
    </template>
    <template v-else-if="kind === 'tag'"><label>分类 <input data-field-path="/payload/category" v-model="p.category" @input="changed"></label><ReferenceList label="父标签" path="/payload/parent_tag_ids" :values="p.parent_tag_ids" @add="add('parent_tag_ids')" @remove="remove('parent_tag_ids', $event)" @changed="changed" /></template>
    <template v-else-if="kind === 'character'"><FormulaList label="属性值" path="/payload/attribute_values" :values="p.attribute_values" :dsl="dsl" @add="add('attribute_values', { output_attribute_id: '', expression: '' })" @remove="remove('attribute_values', $event)" @changed="changed" /><ReferenceList label="技能" path="/payload/skill_ids" :values="p.skill_ids" @add="add('skill_ids')" @remove="remove('skill_ids', $event)" @changed="changed" /><ReferenceList label="物品" path="/payload/item_ids" :values="p.item_ids" @add="add('item_ids')" @remove="remove('item_ids', $event)" @changed="changed" /><TriggerList path="/payload/rule_blocks" :values="p.rule_blocks" @add="add('rule_blocks', { event: 'on_use', target: { type: 'self' }, effect_ids: [] })" @remove="remove('rule_blocks', $event)" @changed="changed" /></template>
    <template v-else-if="kind === 'skill'"><FormulaList label="消耗" path="/payload/costs" :values="p.costs" :dsl="dsl" @add="add('costs', { output_attribute_id: '', expression: '' })" @remove="remove('costs', $event)" @changed="changed" /><label>冷却（毫秒）<input data-field-path="/payload/cooldown" inputmode="numeric" v-model="p.cooldown" @input="changed"></label><TargetSelector path="/payload/target_selector" :value="p.target_selector" @changed="changed" /><ReferenceList label="效果" path="/payload/effect_ids" :values="p.effect_ids" @add="add('effect_ids')" @remove="remove('effect_ids', $event)" @changed="changed" /><TriggerList path="/payload/rule_blocks" :values="p.rule_blocks" @add="add('rule_blocks', { event: 'on_use', target: { type: 'self' }, effect_ids: [] })" @remove="remove('rule_blocks', $event)" @changed="changed" /></template>
    <template v-else-if="kind === 'item'"><label>槽位 <input data-field-path="/payload/slot" v-model="p.slot" @input="changed"></label><ReferenceList label="效果" path="/payload/effect_ids" :values="p.effect_ids" @add="add('effect_ids')" @remove="remove('effect_ids', $event)" @changed="changed" /><ModifierList path="/payload/attribute_modifiers" :values="p.attribute_modifiers" @add="add('attribute_modifiers', { attribute_id: '', operation: 'Add', value: '0' })" @remove="remove('attribute_modifiers', $event)" @changed="changed" /><ReferenceList label="强化标签" path="/payload/enhance_tag_ids" :values="p.enhance_tag_ids" @add="add('enhance_tag_ids')" @remove="remove('enhance_tag_ids', $event)" @changed="changed" /><TriggerList path="/payload/rule_blocks" :values="p.rule_blocks" @add="add('rule_blocks', { event: 'on_use', target: { type: 'self' }, effect_ids: [] })" @remove="remove('rule_blocks', $event)" @changed="changed" /></template>
    <template v-else><label>持续时间（毫秒）<input data-field-path="/payload/duration" inputmode="numeric" v-model="p.duration" @input="changed"></label><ModifierList path="/payload/modifiers" :values="p.modifiers" @add="add('modifiers', { attribute_id: '', operation: 'Add', value: '0' })" @remove="remove('modifiers', $event)" @changed="changed" /><TriggerList label="触发规则" path="/payload/trigger_blocks" :values="p.trigger_blocks" @add="add('trigger_blocks', { event: 'on_use', target: { type: 'self' }, effect_ids: [] })" @remove="remove('trigger_blocks', $event)" @changed="changed" /><fieldset><legend>叠加规则</legend><label>操作 <select data-field-path="/payload/stack_rule/operation" v-model="p.stack_rule.operation" @change="changed"><option>Add</option><option>Multiply</option><option>Override</option><option>Max</option><option>Min</option></select></label><label>优先级 <input data-field-path="/payload/stack_rule/priority" inputmode="numeric" v-model="p.stack_rule.priority" @input="changed"></label><label>最大层数 <input data-field-path="/payload/stack_rule/max_stacks" inputmode="numeric" v-model="p.stack_rule.max_stacks" @input="changed"></label><label>刷新策略 <select data-field-path="/payload/stack_rule/refresh_policy" v-model="p.stack_rule.refresh_policy" @change="changed"><option>refresh</option><option>replace</option><option>ignore</option></select></label><label>上限 <input data-field-path="/payload/stack_rule/cap" inputmode="decimal" v-model="p.stack_rule.cap" @input="changed"></label></fieldset></template>
  </fieldset>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({ components: {
  ReferenceList: defineComponent({ props: { label: String, path: { type: String, required: true }, values: { type: Array, required: true } }, emits: ['add','remove','changed'], template: '<fieldset><legend>{{ label }}（UUID）</legend><div v-for="(_, i) in values" :key="i"><input v-model="values[i]" :data-field-path="`${path}/${i}`" :aria-label="`${label} ${i + 1}`" @input="$emit(\'changed\')"><button type="button" @click="$emit(\'remove\', i)">移除</button></div><button type="button" @click="$emit(\'add\')">添加{{ label }}</button></fieldset>' }),
  FormulaList: defineComponent({ props: { label: String, path: { type: String, required: true }, values: { type: Array, required: true }, dsl: Object }, emits: ['add','remove','changed'], data: () => ({ feedback: {} as Record<number, string>, timers: {} as Record<number, number> }), methods: { schedule(row: { expression?: string }, index: number) { window.clearTimeout(this.timers[index]); this.timers[index] = window.setTimeout(() => { this.feedback[index] = row.expression?.includes('${') && !row.expression.includes('}') ? '选择器 token 尚未闭合；服务端保存时会做最终校验。' : '本地提示仅供编辑；保存和校验以服务端 DSL 为准。' }, 250) }, insertSelector(row: { expression?: string }, scope: string, index: number) { row.expression = `${row.expression ?? ''}${`$`}{${scope}:symbol}`; this.schedule(row, index); this.$emit('changed') }, selectorTokens(expression: string) { return expression.match(/\\$\\{(?:self|source|target|scenario):[^}]+\\}/g) ?? [] } }, template: '<fieldset><legend>{{ label }}</legend><div v-for="(row, i) in values" :key="i"><label>输出属性 UUID <input v-model="row.output_attribute_id" :data-field-path="`${path}/${i}/output_attribute_id`" @input="$emit(\'changed\')"></label><label>表达式 <input v-model="row.expression" :data-field-path="`${path}/${i}/expression`" :list="`formula-suggestions-${path}-${i}`" @input="schedule(row, i); $emit(\'changed\')"></label><datalist v-if="dsl" :id="`formula-suggestions-${path}-${i}`"><option v-for="fn in dsl.functions" :key="`fn-${fn.name}`" :value="`${fn.name}(`"></option><option v-for="unit in dsl.units" :key="`unit-${unit.name}`" :value="`1[${unit.name}]`"></option><option v-for="scope in dsl.scopes" :key="`scope-${scope}`" :value="`${\'$\'}{${scope}:symbol}`"></option></datalist><div v-if="dsl" role="group" aria-label="公式选择器建议"><button v-for="scope in dsl.scopes" :key="scope" type="button" @click="insertSelector(row, scope, i)">插入 {{ scope }} 选择器</button></div><p v-if="feedback[i]" role="status">{{ feedback[i] }}</p><p v-if="selectorTokens(row.expression).length">稳定选择器：<code v-for="token in selectorTokens(row.expression)" :key="token">{{ token }} </code></p><button type="button" @click="$emit(\'remove\', i)">移除</button></div><button type="button" @click="$emit(\'add\')">添加{{ label }}</button></fieldset>' }),
  ModifierList: defineComponent({ props: { path: { type: String, required: true }, values: { type: Array, required: true } }, emits: ['add','remove','changed'], template: '<fieldset><legend>属性修正</legend><div v-for="(row, i) in values" :key="i"><label>属性 UUID <input v-model="row.attribute_id" :data-field-path="`${path}/${i}/attribute_id`" @input="$emit(\'changed\')"></label><label>操作 <select v-model="row.operation" :data-field-path="`${path}/${i}/operation`" @change="$emit(\'changed\')"><option>Add</option><option>Multiply</option><option>Override</option><option>Max</option><option>Min</option></select></label><label>值 <input type="number" v-model.number="row.value" :data-field-path="`${path}/${i}/value`" @input="$emit(\'changed\')"></label><button type="button" @click="$emit(\'remove\', i)">移除</button></div><button type="button" @click="$emit(\'add\')">添加修正</button></fieldset>' }),
  TargetSelector: defineComponent({ props: { path: { type: String, required: true }, value: { type: Object, required: true } }, emits: ['changed'], template: '<fieldset><legend>目标选择器</legend><label>类型 <select v-model="value.type" :data-field-path="`${path}/type`" @change="$emit(\'changed\')"><option>self</option><option>source</option><option>primary_target</option><option>all_targets</option><option>targets_with_tag</option></select></label><label v-if="value.type === \'targets_with_tag\'">标签 UUID <input v-model="value.tag_id" :data-field-path="`${path}/tag_id`" @input="$emit(\'changed\')"></label></fieldset>' }),
  TriggerList: defineComponent({ props: { label: { type: String, default: '规则块' }, path: { type: String, required: true }, values: { type: Array, required: true } }, emits: ['add','remove','changed'], template: '<fieldset><legend>{{ label }}</legend><div v-for="(row, i) in values" :key="i"><label>事件 <select v-model="row.event" :data-field-path="`${path}/${i}/event`" @change="$emit(\'changed\')"><option>on_use</option><option>on_hit</option><option>on_damage</option><option>on_heal</option><option>on_interval</option><option>on_effect_applied</option></select></label><label>条件 <input v-model="row.condition" :data-field-path="`${path}/${i}/condition`" @input="$emit(\'changed\')"></label><fieldset><legend>目标选择器</legend><label>类型 <select v-model="row.target.type" :data-field-path="`${path}/${i}/target/type`" @change="$emit(\'changed\')"><option>self</option><option>source</option><option>primary_target</option><option>all_targets</option><option>targets_with_tag</option></select></label><label v-if="row.target.type === \'targets_with_tag\'">标签 UUID <input v-model="row.target.tag_id" :data-field-path="`${path}/${i}/target/tag_id`" @input="$emit(\'changed\')"></label></fieldset><fieldset><legend>效果（UUID）</legend><div v-for="(_, effectIndex) in row.effect_ids" :key="effectIndex"><input v-model="row.effect_ids[effectIndex]" :data-field-path="`${path}/${i}/effect_ids/${effectIndex}`" @input="$emit(\'changed\')"><button type="button" @click="row.effect_ids.splice(effectIndex, 1); $emit(\'changed\')">移除</button></div><button type="button" @click="row.effect_ids.push(\'\'); $emit(\'changed\')">添加效果</button></fieldset><label>终止预算 <input inputmode="numeric" v-model="row.termination_budget" :data-field-path="`${path}/${i}/termination_budget`" @input="$emit(\'changed\')"></label><button type="button" @click="$emit(\'remove\', i)">移除规则</button></div><button type="button" @click="$emit(\'add\')">添加规则</button></fieldset>' }),
} })
</script>
