<script setup lang="ts">
import { computed } from 'vue'
import type { EntityKind, Payload } from '@/forms/registry'

const props = defineProps<{ kind: EntityKind; modelValue: Payload }>()
const emit = defineEmits<{ 'update:modelValue': [value: Payload]; changed: [] }>()
const p = computed(() => props.modelValue as unknown as Record<string, any>)
function changed() { emit('update:modelValue', { ...p.value } as Payload); emit('changed') }
function add(name: string, value: Record<string, unknown> | string = '') { (p.value[name] ??= []).push(value); changed() }
function remove(name: string, index: number) { p.value[name].splice(index, 1); changed() }
</script>
<template>
  <fieldset class="payload-form"><legend>配置字段</legend>
    <template v-if="kind === 'attribute'">
      <label>数值类型 <select v-model="p.value_type" @change="changed"><option>integer</option><option>decimal</option><option>boolean</option></select></label>
      <label>维度 <input v-model="p.dimension" @input="changed"></label><label>基础单位 <input v-model="p.base_unit" @input="changed"></label>
      <label>默认值 <input type="number" v-model.number="p.default" @input="changed"></label><label>最小值 <input type="number" v-model.number="p.min" @input="changed"></label><label>最大值 <input type="number" v-model.number="p.max" @input="changed"></label><label>显示倍率 <input type="number" v-model.number="p.display_scale" @input="changed"></label>
    </template>
    <template v-else-if="kind === 'tag'"><label>分类 <input v-model="p.category" @input="changed"></label><ReferenceList label="父标签" :values="p.parent_tag_ids" @add="add('parent_tag_ids')" @remove="remove('parent_tag_ids', $event)" @changed="changed" /></template>
    <template v-else-if="kind === 'character'"><FormulaList label="属性值" :values="p.attribute_values" @add="add('attribute_values', { output_attribute_id: '', expression: '' })" @remove="remove('attribute_values', $event)" @changed="changed" /><ReferenceList label="技能" :values="p.skill_ids" @add="add('skill_ids')" @remove="remove('skill_ids', $event)" @changed="changed" /><ReferenceList label="物品" :values="p.item_ids" @add="add('item_ids')" @remove="remove('item_ids', $event)" @changed="changed" /><TriggerList :values="p.rule_blocks" @add="add('rule_blocks', { event: 'on_use', target: { type: 'self' }, effect_ids: [] })" @remove="remove('rule_blocks', $event)" @changed="changed" /></template>
    <template v-else-if="kind === 'skill'"><FormulaList label="消耗" :values="p.costs" @add="add('costs', { output_attribute_id: '', expression: '' })" @remove="remove('costs', $event)" @changed="changed" /><label>冷却 <input type="number" min="0" v-model.number="p.cooldown" @input="changed"></label><TargetSelector :value="p.target_selector" @changed="changed" /><ReferenceList label="效果" :values="p.effect_ids" @add="add('effect_ids')" @remove="remove('effect_ids', $event)" @changed="changed" /><TriggerList :values="p.rule_blocks" @add="add('rule_blocks', { event: 'on_use', target: { type: 'self' }, effect_ids: [] })" @remove="remove('rule_blocks', $event)" @changed="changed" /></template>
    <template v-else-if="kind === 'item'"><label>槽位 <input v-model="p.slot" @input="changed"></label><ReferenceList label="效果" :values="p.effect_ids" @add="add('effect_ids')" @remove="remove('effect_ids', $event)" @changed="changed" /><ModifierList :values="p.attribute_modifiers" @add="add('attribute_modifiers', { attribute_id: '', operation: 'Add', value: 0 })" @remove="remove('attribute_modifiers', $event)" @changed="changed" /><ReferenceList label="强化标签" :values="p.enhance_tag_ids" @add="add('enhance_tag_ids')" @remove="remove('enhance_tag_ids', $event)" @changed="changed" /><TriggerList :values="p.rule_blocks" @add="add('rule_blocks', { event: 'on_use', target: { type: 'self' }, effect_ids: [] })" @remove="remove('rule_blocks', $event)" @changed="changed" /></template>
    <template v-else><label>持续时间 <input type="number" min="0" v-model.number="p.duration" @input="changed"></label><ModifierList :values="p.modifiers" @add="add('modifiers', { attribute_id: '', operation: 'Add', value: 0 })" @remove="remove('modifiers', $event)" @changed="changed" /><TriggerList label="触发规则" :values="p.trigger_blocks" @add="add('trigger_blocks', { event: 'on_use', target: { type: 'self' }, effect_ids: [] })" @remove="remove('trigger_blocks', $event)" @changed="changed" /><fieldset><legend>叠加规则</legend><label>操作 <select v-model="p.stack_rule.operation" @change="changed"><option>Add</option><option>Multiply</option><option>Override</option><option>Max</option><option>Min</option></select></label><label>优先级 <input type="number" v-model.number="p.stack_rule.priority" @input="changed"></label><label>最大层数 <input type="number" min="1" v-model.number="p.stack_rule.max_stacks" @input="changed"></label><label>刷新策略 <select v-model="p.stack_rule.refresh_policy" @change="changed"><option>refresh</option><option>replace</option><option>ignore</option></select></label><label>上限 <input type="number" v-model.number="p.stack_rule.cap" @input="changed"></label></fieldset></template>
  </fieldset>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
export default defineComponent({ components: {
  ReferenceList: defineComponent({ props: { label: String, values: { type: Array, required: true } }, emits: ['add','remove','changed'], template: '<fieldset><legend>{{ label }}（UUID）</legend><div v-for="(_, i) in values" :key="i"><input v-model="values[i]" :aria-label="`${label} ${i + 1}`" @input="$emit(\'changed\')"><button type="button" @click="$emit(\'remove\', i)">移除</button></div><button type="button" @click="$emit(\'add\')">添加{{ label }}</button></fieldset>' }),
  FormulaList: defineComponent({ props: { label: String, values: { type: Array, required: true } }, emits: ['add','remove','changed'], template: '<fieldset><legend>{{ label }}</legend><div v-for="(row, i) in values" :key="i"><label>输出属性 UUID <input v-model="row.output_attribute_id" @input="$emit(\'changed\')"></label><label>表达式 <input v-model="row.expression" @input="$emit(\'changed\')"></label><button type="button" @click="$emit(\'remove\', i)">移除</button></div><button type="button" @click="$emit(\'add\')">添加{{ label }}</button></fieldset>' }),
  ModifierList: defineComponent({ props: { values: { type: Array, required: true } }, emits: ['add','remove','changed'], template: '<fieldset><legend>属性修正</legend><div v-for="(row, i) in values" :key="i"><label>属性 UUID <input v-model="row.attribute_id" @input="$emit(\'changed\')"></label><label>操作 <select v-model="row.operation" @change="$emit(\'changed\')"><option>Add</option><option>Multiply</option><option>Override</option><option>Max</option><option>Min</option></select></label><label>值 <input type="number" v-model.number="row.value" @input="$emit(\'changed\')"></label><button type="button" @click="$emit(\'remove\', i)">移除</button></div><button type="button" @click="$emit(\'add\')">添加修正</button></fieldset>' }),
  TargetSelector: defineComponent({ props: { value: { type: Object, required: true } }, emits: ['changed'], template: '<fieldset><legend>目标选择器</legend><label>类型 <select v-model="value.type" @change="$emit(\'changed\')"><option>self</option><option>source</option><option>primary_target</option><option>all_targets</option><option>targets_with_tag</option></select></label><label v-if="value.type === \'targets_with_tag\'">标签 UUID <input v-model="value.tag_id" @input="$emit(\'changed\')"></label></fieldset>' }),
  TriggerList: defineComponent({ props: { label: { type: String, default: '规则块' }, values: { type: Array, required: true } }, emits: ['add','remove','changed'], template: '<fieldset><legend>{{ label }}</legend><div v-for="(row, i) in values" :key="i"><label>事件 <select v-model="row.event" @change="$emit(\'changed\')"><option>on_use</option><option>on_hit</option><option>on_damage</option><option>on_heal</option><option>on_interval</option><option>on_effect_applied</option></select></label><label>条件 <input v-model="row.condition" @input="$emit(\'changed\')"></label><fieldset><legend>目标选择器</legend><label>类型 <select v-model="row.target.type" @change="$emit(\'changed\')"><option>self</option><option>source</option><option>primary_target</option><option>all_targets</option><option>targets_with_tag</option></select></label><label v-if="row.target.type === \'targets_with_tag\'">标签 UUID <input v-model="row.target.tag_id" @input="$emit(\'changed\')"></label></fieldset><fieldset><legend>效果（UUID）</legend><div v-for="(_, effectIndex) in row.effect_ids" :key="effectIndex"><input v-model="row.effect_ids[effectIndex]" @input="$emit(\'changed\')"><button type="button" @click="row.effect_ids.splice(effectIndex, 1); $emit(\'changed\')">移除</button></div><button type="button" @click="row.effect_ids.push(\'\'); $emit(\'changed\')">添加效果</button></fieldset><label>终止预算 <input type="number" min="1" v-model.number="row.termination_budget" @input="$emit(\'changed\')"></label><button type="button" @click="$emit(\'remove\', i)">移除规则</button></div><button type="button" @click="$emit(\'add\')">添加规则</button></fieldset>' }),
} })
</script>
